### PR TITLE
feat: support argo applicationset

### PR DESCRIPTION
**Pull request by wowq**
Support update argo applicationset version

### CODE REVIEW

**Comment by msvticket** [comment]
The test failed:


```
 FAIL: TestModifyApplicationFiles (0.05s)
		    applications_test.go:19: using dir /tmp/TestModifyApplicationFiles1492847697/001
		    files.go:84: 
		        	Error Trace:	/workspace/source/pkg/cmd/argo/promote/files.go:84
		        	            				/workspace/source/pkg/cmd/argo/promote/applications_test.go:52
		        	Error:      	Not equal: 
		        	            	expected: "apiVersion: argoproj.io/v1alpha1\nkind: ApplicationSet\nmetadata:\n  name: my-v3-lts-node\n  namespace: argocd\n  annotations:\n    gitops.jenkins-x.io/sourceRepoUrl: [https://github.com/myorg/myrepo.git\nspec:\n](https://github.com/myorg/myrepo.git/nspec:/n)  generators:\n  - clusters: {}\n  template:\n    metadata:\n      name: \"{{name}}-my-v3-lts-node\"\n      annotations:\n        test1: test1\n    spec:\n      destination:\n        namespace: cheese\n        server: [https://kubernetes.default.svc\n](https://kubernetes.default.svc/n)      project: default\n      source:\n        path: charts/my-chart\n        repoURL: [https://github.com/myorg/myrepo.git\n](https://github.com/myorg/myrepo.git/n)        targetRevision: v1.2.3\n      syncPolicy:\n        automated:\n          selfHeal: true\n        syncOptions:\n        - CreateNamespace=true\n"
		        	            	actual  : "apiVersion: argoproj.io/v1alpha1\nkind: ApplicationSet\nmetadata:\n  name: my-v3-lts-node\n  namespace: argocd\n  annotations:\n    gitops.jenkins-x.io/sourceRepoUrl: [https://github.com/myorg/myrepo.git\nspec:\n](https://github.com/myorg/myrepo.git/nspec:/n)  generators:\n  - clusters: {}\n  template:\n    metadata:\n      name: \"{{name}}-my-v3-lts-node\"\n      annotations:\n        test1: test1\n    spec:\n      destination:\n        namespace: cheese\n        server: {? {server: ''} : ''}\n      project: default\n      source:\n        path: charts/my-chart\n        repoURL: [https://github.com/myorg/myrepo.git\n](https://github.com/myorg/myrepo.git/n)        targetRevision: v1.2.3\n      syncPolicy:\n        automated:\n          selfHeal: true\n        syncOptions:\n        - CreateNamespace=true\n"
		        	            	
		        	            	Diff:
		        	            	--- Expected
		        	            	+++ Actual
		        	            	@@ -18,3 +18,3 @@
		        	            	         namespace: cheese
		        	            	-        server: https://kubernetes.default.svc/
		        	            	+        server: {? {server: ''} : ''}
		        	            	       project: default
		        	Test:       	TestModifyApplicationFiles
		        	Messages:   	comparing text content of files /tmp/TestModifyApplicationFiles1492847697/001/simple/expected/myapp-appset.yaml and /tmp/TestModifyApplicationFiles1492847697/001/simple/source/myapp-appset.yaml
 FAIL	github.com/jenkins-x-plugins/jx-updatebot/pkg/cmd/argo/promote	0.211s
```

**Comment by wowq** [comment]
@msvticket  fixed

**Pull request merged**
