### PR TITLE
feat: add interactive sync mode

### PR DESCRIPTION
**Pull request by rast1025**
Adds interactive mode with ability to choose charts to sync
Use `jx updatebot sync --interactive`

### CODE REVIEW

**Comment by msvticket** [comment]
@rast1025 If you resolve the conflicts we could get this merged

**Comment by tomhobson** [comment]
@msvticket, rast1025 was on my team at my org, he moved onto bigger and better things, so I've merged master into this

**Comment by msvticket** [comment]
@tomhobson If you fix the the test failures I can get it merged

**Review by msvticket — CHANGES_REQUESTED** [review]
Make the lint and pr jobs pass

**Pull request closed without merging**
